// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphqlgen

type FesEvent struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Speaker string `json:"speaker"`
}

type GetFesEventPayload struct {
	FesEvents []*FesEvent `json:"fesEvents"`
}

type SaveFesEevntInput struct {
	Title   string `json:"title"`
	Speaker string `json:"speaker"`
}
